name: streak
description: An App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  google_sign_in_all_platforms: ^2.0.0
  flutter_dotenv: ^6.0.0

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  go_router: ^16.0.0
  intl: ^0.20.2
  uuid: ^4.5.2
  shared_preferences: ^2.5.3
  hive: ^2.2.3 # <--- CHANGE TO LATEST STABLE (e.g., ^2.2.3, but latest is often preferred)
  hive_flutter: ^1.1.0 # <--- CHANGE TO LATEST STABLE (e.g., ^1.1.0, but latest is often preferred)

  cloud_firestore: ^5.6.11

  path_provider: ^2.1.5
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.9

  isar_flutter_libs: ^4.0.0-dev.13 # Also note Isar is a dev version, which can introduce instability
  collection: ^1.19.1
  showcaseview: ^5.0.1
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1 # <--- CHANGE TO LATEST STABLE (e.g., ^2.0.1, but latest is often preferred)

  flutter_lints: ^6.0.0

  build_runner: 2.5.4
  riverpod_generator: 2.6.3

  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
